url: http://localhost:8080/index

spring:
  # Thymeleaf config
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  # database config h2 consider change to postgres
  datasource:
    url: jdbc:h2:mem:testdb
    #url: jdbc:h2:file:~/testdb #Persistente database mode
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: true      # show sql executed in the project
    hibernate:
      ddl-auto: update  # create and update tables in the start of the project
  # just in h2 database to configuration interface access http://localhost:8080/h2-console
  h2:
    console:
      enabled: true
      path: /h2-console
  #Flyway config to init some inserts into database      
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    root: info
    br.com.agnes: debug
